### ISSUE TITLE
What build environment? Still works?

### ISSUE THREAD

**Issue by CBroz1** [Booster1212/github-issue-bot#27]
Hi - I'm not super familiar with js, but trying to add a bot to my server. What build environment should I be using? The start command `rmdir /s ...` implied windows to me, but I'm getting an error (full log below)
```
npm ERR! could not determine executable to run
```
I also tried `npm run build && node ./prod/index.js` on OSX. It was running, but seemingly with some depreciation warnings for `discordjs/collection` and `discordjs/builder`. Are those dependencies that no longer work?

Thanks for your work here!

logfile:
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\cbroz1\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.19.1
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\cbroz1\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\cbroz1\Documents\creative\github-issue-bot\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\cbroz1\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\cbroz1\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec swc ./src --out-dir prod
23 verbose argv "exec" "--" "swc" "./src" "--out-dir" "prod"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\cbroz1\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\cbroz1\AppData\Local\npm-cache\_logs\2022-09-05T15_48_58_306Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 27ms
33 silly logfile start cleaning logs, removing 2 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 1ms
36 timing arborist:ctor Completed in 1ms
37 http fetch GET 200 https://registry.npmjs.org/swc 438ms (cache revalidated)
38 timing command:exec Completed in 469ms
39 verbose stack Error: could not determine executable to run
39 verbose stack     at getBinFromManifest (C:\Users\cbroz1\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
39 verbose stack     at exec (C:\Users\cbroz1\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:173:15)
39 verbose stack     at async module.exports (C:\Users\cbroz1\AppData\Roaming\npm\node_modules\npm\lib\cli.js:78:5)
40 verbose pkgid swc@1.0.11
41 verbose cwd C:\Users\cbroz1\Documents\creative\github-issue-bot
42 verbose Windows_NT 10.0.19044
43 verbose node v16.15.1
44 verbose npm  v8.19.1
45 error could not determine executable to run
46 verbose exit 1
47 timing npm Completed in 664ms
48 verbose code 1
49 error A complete log of this run can be found in:
49 error     C:\Users\cbroz1\AppData\Local\npm-cache\_logs\2022-09-05T15_48_58_306Z-debug-0.log
```

**Comment by Booster1212** [comment]
I think bot needs update for DiscordJS 14, i'll have a look soon, thanks
